# Generated by Django 4.1 on 2022-08-24 23:05

import certificados.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=170)),
                ('limite_horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('turma', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.curso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.IntegerField()),
                ('titulo', models.CharField(max_length=150)),
                ('data_emissao', models.DateTimeField()),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('situacao', models.SmallIntegerField(default=2)),
                ('imagem', models.FileField(upload_to='certificados/', validators=[certificados.validators.validate_file_extension])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.categoria')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.curso'),
        ),
    ]
