# Generated by Django 4.1 on 2022-08-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='observacao',
            field=models.CharField(default='', max_length=200),
        ),
    ]
