# Generated by Django 4.1 on 2022-08-27 15:12

import certificados.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0004_alter_certificado_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='data_emissao',
            field=models.DateTimeField(help_text='Se a atividade aconteceu em múltiplos dias informe apenas a data inicial', verbose_name='Data da atividade'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='imagem',
            field=models.FileField(help_text='Certifique-se de enviar o certificado alinhado, com boa resolução e no máximo 10MB (Preferencialmente em PDF)', upload_to='certificados/', validators=[certificados.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='titulo',
            field=models.CharField(help_text='Informe o título completo da atividade', max_length=150),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='turma',
            field=models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], max_length=4),
        ),
    ]
