# Generated by Django 4.1 on 2022-08-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0007_alter_perfil_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='semestres',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
