# Generated by Django 4.1 on 2022-08-28 03:22

import certificados.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0008_curso_semestres'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='redefinir_senha',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='horas',
            field=models.IntegerField(verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='imagem',
            field=models.FileField(help_text='Certifique-se de enviar o certificado alinhado, com boa resolução e no máximo 10MB (Preferencialmente em PDF)', upload_to='certificados/', validators=[certificados.validators.validate_file_extension], verbose_name='Certificado'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='titulo',
            field=models.CharField(help_text='Informe o título completo da atividade conforme o certificado', max_length=150, verbose_name='Título'),
        ),
    ]
