# Generated by Django 4.1 on 2022-08-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0009_perfil_redefinir_senha_alter_certificado_horas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='situacao',
            field=models.SmallIntegerField(choices=[(1, 'Aprovado'), (2, 'Em análise'), (3, 'Recusado'), (4, 'Erro')], default=2),
        ),
    ]
